### ISSUE TITLE
Coursera error - Unable to access Taskgrader

### ISSUE THREAD

**Issue by catherinechoww** [France-ioi/taskgrader#120] opened 2023-12-20 22:46 UTC
Hi @mblockelet,

I trust you are doing well. There's an issue in Coursera, where users are able to access codecasts and the problem statement page of assignments. However, there is no tab for "solve" and are thus unable to write and submit their code. See screenshot of an example:

<img width="1174" alt="Screen Shot 2023-12-20 at 12 42 37 PM" src="https://github.com/France-ioi/taskgrader/assets/98115742/9741f15f-f6fb-4070-9a08-1c52cc31c4a9">

**Comment by mblockelet** [comment] 2023-12-21 00:11
Hello, thank you for reporting this issue. We are working on it, and hope to have a fix very soon, I'll keep you updated when this is fixed!

**Comment by mblockelet** [comment] 2023-12-21 09:02
Hi @catherinechoww , the issue is now fixed, thank you again for reporting it!

**Closed by mblockelet** 2023-12-21 09:02 UTC
